development:
  adapter: postgresql
  encoding: utf8
  database: cubies_development
  pool: 5
  username: Solitude
  password: ''
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: cubies_test
  pool: 5
  username: Solitude
  password: ''
  host: localhost
